/* 단어 사전: 동물 — 계약
 *  CATS.push({ id, name, emoji })  ·  WORDS.push({ ko, alt:[], en, read, emoji, cat })
 *  - ko: 대표 한국어(매칭용), alt: 발음 변형·유의어(선택), en: 영어(소문자),
 *    read: 한글 발음 표기, emoji: 그림 1개, cat: 카테고리 id
 *  - en은 사전 전체에서 유일해야 함. 1글자 ko는 오탐 주의(가급적 2글자+)
 */
window.WORDS = window.WORDS || [];
window.CATS = window.CATS || [];

CATS.push({ id: 'animals', name: '동물', emoji: '🐘' });

[
  { ko: '코끼리', alt: ['꼬끼리'], en: 'elephant', read: '엘리펀트', emoji: '🐘' },
  { ko: '강아지', alt: ['개', '멍멍이'], en: 'dog', read: '도그', emoji: '🐶' },
  { ko: '고양이', alt: ['야옹이', '냐옹이'], en: 'cat', read: '캣', emoji: '🐱' },
  { ko: '사자', en: 'lion', read: '라이언', emoji: '🦁' },
  { ko: '호랑이', alt: ['호랭이'], en: 'tiger', read: '타이거', emoji: '🐯' },
  { ko: '곰', alt: ['곰돌이'], en: 'bear', read: '베어', emoji: '🐻' },
  { ko: '토끼', alt: ['토깽이'], en: 'rabbit', read: '래빗', emoji: '🐰' },
  { ko: '여우', en: 'fox', read: '폭스', emoji: '🦊' },
  { ko: '원숭이', alt: ['원숭이들'], en: 'monkey', read: '멍키', emoji: '🐵' },
  { ko: '판다', alt: ['팬더', '판다곰'], en: 'panda', read: '팬다', emoji: '🐼' },
  { ko: '코알라', en: 'koala', read: '코알라', emoji: '🐨' },
  { ko: '기린', en: 'giraffe', read: '지래프', emoji: '🦒' },
  { ko: '얼룩말', en: 'zebra', read: '지브라', emoji: '🦓' },
  { ko: '하마', en: 'hippo', read: '히포', emoji: '🦛' },
  { ko: '코뿔소', en: 'rhino', read: '라이노', emoji: '🦏' },
  { ko: '악어', en: 'crocodile', read: '크로커다일', emoji: '🐊' },
  { ko: '뱀', en: 'snake', read: '스네이크', emoji: '🐍' },
  { ko: '거북이', alt: ['거북'], en: 'turtle', read: '터틀', emoji: '🐢' },
  { ko: '개구리', en: 'frog', read: '프로그', emoji: '🐸' },
  { ko: '돼지', alt: ['꿀꿀이'], en: 'pig', read: '피그', emoji: '🐷' },
  { ko: '소', alt: ['젖소', '음매'], en: 'cow', read: '카우', emoji: '🐮' },
  { ko: '말', alt: ['망아지'], en: 'horse', read: '호스', emoji: '🐴' },
  { ko: '양', alt: ['양털'], en: 'sheep', read: '쉽', emoji: '🐑' },
  { ko: '염소', en: 'goat', read: '고트', emoji: '🐐' },
  { ko: '닭', alt: ['꼬꼬닭', '꼬끼오'], en: 'chicken', read: '치킨', emoji: '🐔' },
  { ko: '병아리', en: 'chick', read: '칙', emoji: '🐤' },
  { ko: '오리', alt: ['꽥꽥이'], en: 'duck', read: '덕', emoji: '🦆' },
  { ko: '펭귄', en: 'penguin', read: '펭귄', emoji: '🐧' },
  { ko: '부엉이', alt: ['올빼미'], en: 'owl', read: '아울', emoji: '🦉' },
  { ko: '독수리', en: 'eagle', read: '이글', emoji: '🦅' },
  { ko: '새', alt: ['새들'], en: 'bird', read: '버드', emoji: '🐦' },
  { ko: '물고기', alt: ['생선', '붕어'], en: 'fish', read: '피시', emoji: '🐟' },
  { ko: '상어', en: 'shark', read: '샤크', emoji: '🦈' },
  { ko: '고래', en: 'whale', read: '웨일', emoji: '🐳' },
  { ko: '돌고래', en: 'dolphin', read: '돌핀', emoji: '🐬' },
  { ko: '문어', en: 'octopus', read: '옥토퍼스', emoji: '🐙' },
  { ko: '게', alt: ['꽃게'], en: 'crab', read: '크랩', emoji: '🦀' },
  { ko: '나비', en: 'butterfly', read: '버터플라이', emoji: '🦋' },
  { ko: '벌', alt: ['꿀벌'], en: 'bee', read: '비', emoji: '🐝' },
  { ko: '개미', en: 'ant', read: '앤트', emoji: '🐜' },
  { ko: '무당벌레', en: 'ladybug', read: '레이디버그', emoji: '🐞' },
  { ko: '달팽이', en: 'snail', read: '스네일', emoji: '🐌' },
  { ko: '공룡', en: 'dinosaur', read: '다이너소어', emoji: '🦕' },
  { ko: '쥐', alt: ['생쥐'], en: 'mouse', read: '마우스', emoji: '🐭' },
  { ko: '다람쥐', en: 'squirrel', read: '스쿼럴', emoji: '🐿️' },
  { ko: '늑대', en: 'wolf', read: '울프', emoji: '🐺' },
  { ko: '사슴', en: 'deer', read: '디어', emoji: '🦌' },
  { ko: '낙타', en: 'camel', read: '캐멀', emoji: '🐫' },
  { ko: '캥거루', en: 'kangaroo', read: '캥거루', emoji: '🦘' },
  /* --- 곤충 친구들 --- */
  { ko: '잠자리', en: 'dragonfly', read: '드래곤플라이', emoji: '🪰' },
  { ko: '메뚜기', en: 'grasshopper', read: '그래스호퍼', emoji: '🦗' },
  { ko: '거미', en: 'spider', read: '스파이더', emoji: '🕷️' },
  { ko: '모기', en: 'mosquito', read: '모스키토', emoji: '🦟' },
  { ko: '파리', en: 'housefly', read: '하우스플라이', emoji: '🪰' },
  { ko: '반딧불이', alt: ['반딧불', '개똥벌레'], en: 'firefly', read: '파이어플라이', emoji: '🪲' },
  { ko: '사마귀', en: 'mantis', read: '맨티스', emoji: '🦗' },
  { ko: '바퀴벌레', en: 'cockroach', read: '카크로치', emoji: '🪳' },
  { ko: '애벌레', en: 'caterpillar', read: '캐터필러', emoji: '🐛' },
  { ko: '전갈', en: 'scorpion', read: '스콜피온', emoji: '🦂' },
  { ko: '지렁이', en: 'worm', read: '웜', emoji: '🪱' },
  { ko: '귀뚜라미', en: 'cricket', read: '크리켓', emoji: '🦗' },
  { ko: '풍뎅이', alt: ['딱정벌레'], en: 'beetle', read: '비틀', emoji: '🪲' },
  /* --- 새 친구들 --- */
  { ko: '비둘기', en: 'pigeon', read: '피전', emoji: '🕊️' },
  { ko: '참새', en: 'sparrow', read: '스패로우', emoji: '🐦' },
  { ko: '까치', en: 'magpie', read: '맥파이', emoji: '🐦‍⬛' },
  { ko: '까마귀', en: 'crow', read: '크로우', emoji: '🐦‍⬛' },
  { ko: '제비', en: 'swallow', read: '스왈로우', emoji: '🐦' },
  { ko: '공작', alt: ['공작새'], en: 'peacock', read: '피콕', emoji: '🦚' },
  { ko: '앵무새', en: 'parrot', read: '패럿', emoji: '🦜' },
  { ko: '백조', en: 'swan', read: '스완', emoji: '🦢' },
  { ko: '플라밍고', alt: ['홍학'], en: 'flamingo', read: '플라밍고', emoji: '🦩' },
  { ko: '거위', en: 'goose', read: '구스', emoji: '🪿' },
  { ko: '칠면조', en: 'turkey', read: '터키', emoji: '🦃' },
  { ko: '도도새', en: 'dodo', read: '도도', emoji: '🦤' },
  /* --- 바다 친구들 --- */
  { ko: '새우', en: 'shrimp', read: '쉬림프', emoji: '🦐' },
  { ko: '오징어', en: 'squid', read: '스퀴드', emoji: '🦑' },
  { ko: '해파리', en: 'jellyfish', read: '젤리피시', emoji: '🪼' },
  { ko: '불가사리', en: 'starfish', read: '스타피시', emoji: '⭐' },
  { ko: '소라', en: 'conch', read: '콩크', emoji: '🐚' },
  { ko: '조개', alt: ['조개껍질'], en: 'clam', read: '클램', emoji: '🦪' },
  { ko: '물개', alt: ['물범', '바다표범'], en: 'seal', read: '실', emoji: '🦭' },
  { ko: '해달', en: 'sea otter', read: '씨 오터', emoji: '🦦' },
  { ko: '수달', en: 'otter', read: '오터', emoji: '🦦' },
  { ko: '복어', en: 'pufferfish', read: '퍼퍼피시', emoji: '🐡' },
  { ko: '열대어', en: 'tropical fish', read: '트로피컬 피시', emoji: '🐠' },
  { ko: '바닷가재', alt: ['랍스터', '가재'], en: 'lobster', read: '랍스터', emoji: '🦞' },
  /* --- 여러 동물 친구들 --- */
  { ko: '고릴라', en: 'gorilla', read: '고릴라', emoji: '🦍' },
  { ko: '침팬지', en: 'chimpanzee', read: '침팬지', emoji: '🐒' },
  { ko: '오랑우탄', en: 'orangutan', read: '오랑우탄', emoji: '🦧' },
  { ko: '치타', en: 'cheetah', read: '치타', emoji: '🐆' },
  { ko: '표범', en: 'leopard', read: '레오파드', emoji: '🐆' },
  { ko: '고슴도치', en: 'hedgehog', read: '헤지호그', emoji: '🦔' },
  { ko: '너구리', en: 'raccoon', read: '라쿤', emoji: '🦝' },
  { ko: '스컹크', en: 'skunk', read: '스컹크', emoji: '🦨' },
  { ko: '박쥐', en: 'bat', read: '배트', emoji: '🦇' },
  { ko: '햄스터', en: 'hamster', read: '햄스터', emoji: '🐹' },
  { ko: '당나귀', en: 'donkey', read: '동키', emoji: '🫏' },
  { ko: '황소', en: 'ox', read: '옥스', emoji: '🐂' },
  { ko: '물소', en: 'water buffalo', read: '워터 버팔로', emoji: '🐃' },
  { ko: '들소', alt: ['버팔로'], en: 'bison', read: '바이슨', emoji: '🦬' },
  { ko: '순록', alt: ['루돌프'], en: 'reindeer', read: '레인디어', emoji: '🦌' },
  { ko: '라마', alt: ['알파카'], en: 'llama', read: '라마', emoji: '🦙' },
  { ko: '나무늘보', alt: ['늘보'], en: 'sloth', read: '슬로스', emoji: '🦥' },
  { ko: '비버', en: 'beaver', read: '비버', emoji: '🦫' },
  { ko: '오소리', en: 'badger', read: '배저', emoji: '🦡' },
  { ko: '멧돼지', en: 'boar', read: '보어', emoji: '🐗' },
  { ko: '도마뱀', en: 'lizard', read: '리저드', emoji: '🦎' },
  { ko: '두꺼비', en: 'toad', read: '토드', emoji: '🐸' },
  { ko: '유니콘', en: 'unicorn', read: '유니콘', emoji: '🦄' },
  { ko: '용', alt: ['드래곤'], en: 'dragon', read: '드래곤', emoji: '🐉' },
  { ko: '매머드', alt: ['맘모스'], en: 'mammoth', read: '매머드', emoji: '🦣' },
  /* --- 공룡 친구들 --- */
  { ko: '티라노사우루스', alt: ['티라노', '티렉스'], en: 'tyrannosaurus', read: '티라노사우루스', emoji: '🦖' },
  { ko: '트리케라톱스', en: 'triceratops', read: '트리케라톱스', emoji: '🦕' }
].forEach(w => { w.cat = 'animals'; WORDS.push(w); });
