/* 단어 사전: 몸·가족 — 계약
 *  CATS.push({ id, name, emoji })  ·  WORDS.push({ ko, alt:[], en, read, emoji, cat })
 *  - ko: 대표 한국어(매칭용), alt: 발음 변형·유의어(선택), en: 영어(소문자),
 *    read: 한글 발음 표기, emoji: 그림 1개, cat: 카테고리 id
 *  - en은 사전 전체에서 유일해야 함. 1글자 ko는 오탐 주의(가급적 2글자+)
 */
window.WORDS = window.WORDS || [];
window.CATS = window.CATS || [];

CATS.push({ id: 'body', name: '몸·가족', emoji: '👋' });

[
  // ── 몸 ──
  { ko: '머리', en: 'head', read: '헤드', emoji: '👤' },
  { ko: '얼굴', en: 'face', read: '페이스', emoji: '🙂' },
  { ko: '눈동자', alt: ['눈알'], en: 'eye', read: '아이', emoji: '👁️' },
  { ko: '코', en: 'nose', read: '노즈', emoji: '👃' },
  { ko: '입', en: 'mouth', read: '마우쓰', emoji: '👄' },
  { ko: '입술', en: 'lips', read: '립스', emoji: '💋' },
  { ko: '귀', en: 'ear', read: '이어', emoji: '👂' },
  { ko: '이빨', alt: ['치아'], en: 'tooth', read: '투쓰', emoji: '🦷' },
  { ko: '혓바닥', en: 'tongue', read: '텅', emoji: '👅' },
  { ko: '어깨', en: 'shoulder', read: '숄더', emoji: '🤷' },
  { ko: '팔', en: 'arm', read: '암', emoji: '💪' },
  { ko: '팔꿈치', en: 'elbow', read: '엘보', emoji: '🦾' },
  { ko: '손', alt: ['손바닥'], en: 'hand', read: '핸드', emoji: '✋' },
  { ko: '손가락', en: 'finger', read: '핑거', emoji: '☝️' },
  { ko: '엄지', alt: ['엄지척'], en: 'thumb', read: '썸', emoji: '👍' },
  { ko: '주먹', en: 'fist', read: '피스트', emoji: '✊' },
  { ko: '다리', en: 'leg', read: '레그', emoji: '🦵' },
  { ko: '무릎', en: 'knee', read: '니', emoji: '🧎' },
  { ko: '발', en: 'foot', read: '풋', emoji: '🦶' },
  { ko: '발가락', en: 'toe', read: '토우', emoji: '🦶' },
  { ko: '엉덩이', alt: ['궁둥이'], en: 'hip', read: '힙', emoji: '🍑' },
  { ko: '머리카락', alt: ['머리칼'], en: 'hair', read: '헤어', emoji: '💇' },
  { ko: '눈썹', en: 'eyebrow', read: '아이브로우', emoji: '🤨' },
  { ko: '심장', alt: ['두근두근'], en: 'heart', read: '하트', emoji: '💗' },
  { ko: '뼈', alt: ['뼈다귀'], en: 'bone', read: '본', emoji: '🦴' },
  // ── 가족 ──
  { ko: '엄마', alt: ['어머니'], en: 'mom', read: '맘', emoji: '👩' },
  { ko: '아빠', alt: ['아버지'], en: 'dad', read: '대드', emoji: '👨' },
  { ko: '아기', alt: ['애기', '아가'], en: 'baby', read: '베이비', emoji: '👶' },
  { ko: '할머니', alt: ['할매'], en: 'grandma', read: '그랜마', emoji: '👵' },
  { ko: '할아버지', alt: ['할배'], en: 'grandpa', read: '그랜파', emoji: '👴' },
  { ko: '오빠', alt: ['형아', '남동생'], en: 'brother', read: '브라더', emoji: '👬' },
  { ko: '언니', alt: ['누나', '여동생'], en: 'sister', read: '시스터', emoji: '👭' },
  { ko: '남자아이', alt: ['남자', '사내아이'], en: 'boy', read: '보이', emoji: '👦' },
  { ko: '여자아이', alt: ['여자'], en: 'girl', read: '걸', emoji: '👧' },
  { ko: '가족', en: 'family', read: '패밀리', emoji: '👨‍👩‍👧‍👦' },
  { ko: '친구', alt: ['친구들'], en: 'friend', read: '프렌드', emoji: '🧑‍🤝‍🧑' },
  { ko: '쌍둥이', en: 'twins', read: '트윈스', emoji: '👯' },
  { ko: '이모', alt: ['고모', '숙모'], en: 'aunt', read: '앤트', emoji: '👩‍🦰' },
  { ko: '삼촌', alt: ['외삼촌'], en: 'uncle', read: '엉클', emoji: '👨‍🦱' },
  { ko: '사람', en: 'person', read: '퍼슨', emoji: '🧍' },
  { ko: '어린이', alt: ['아이', '꼬마'], en: 'child', read: '차일드', emoji: '🧒' },
  // ── 사람·직업 ──
  { ko: '의사', alt: ['의사 선생님'], en: 'doctor', read: '닥터', emoji: '👨‍⚕️' },
  { ko: '간호사', alt: ['간호사 선생님'], en: 'nurse', read: '널스', emoji: '👩‍⚕️' },
  { ko: '경찰관', alt: ['경찰', '경찰 아저씨'], en: 'police', read: '폴리스', emoji: '👮' },
  { ko: '소방관', alt: ['소방관 아저씨'], en: 'fireman', read: '파이어맨', emoji: '👨‍🚒' },
  { ko: '선생님', en: 'teacher', read: '티처', emoji: '🧑‍🏫' },
  { ko: '요리사', en: 'chef', read: '셰프', emoji: '👨‍🍳' },
  { ko: '농부', alt: ['농부 아저씨'], en: 'farmer', read: '파머', emoji: '👩‍🌾' },
  { ko: '왕', alt: ['임금님'], en: 'king', read: '킹', emoji: '🤴' },
  { ko: '여왕', alt: ['여왕님'], en: 'queen', read: '퀸', emoji: '🫅' },
  { ko: '공주', alt: ['공주님'], en: 'princess', read: '프린세스', emoji: '👸' },
  { ko: '우주비행사', alt: ['우주인'], en: 'astronaut', read: '애스트로넛', emoji: '🧑‍🚀' },
  { ko: '가수', en: 'singer', read: '싱어', emoji: '🎤' },
  { ko: '화가', en: 'painter', read: '페인터', emoji: '🎨' },
  { ko: '마법사', alt: ['마술사'], en: 'wizard', read: '위저드', emoji: '🧙' },
  { ko: '요정', en: 'fairy', read: '페어리', emoji: '🧚' },
  { ko: '산타', alt: ['산타클로스', '산타 할아버지'], en: 'santa', read: '산타', emoji: '🎅' },
  { ko: '천사', en: 'angel', read: '엔젤', emoji: '👼' },
  { ko: '영웅', alt: ['슈퍼히어로'], en: 'hero', read: '히어로', emoji: '🦸' },
  { ko: '수염', alt: ['턱수염'], en: 'beard', read: '비어드', emoji: '🧔' },
  { ko: '유령', alt: ['귀신'], en: 'ghost', read: '고스트', emoji: '👻' },

  // ── 몸 (추가) ──
  { ko: '이마', en: 'forehead', read: '포어헤드', emoji: '🧑' },
  { ko: '볼', alt: ['볼따구'], en: 'cheek', read: '치크', emoji: '😊' },
  { ko: '목', alt: ['목덜미'], en: 'neck', read: '넥', emoji: '🧣' },
  { ko: '손톱', en: 'fingernail', read: '핑거네일', emoji: '💅' },
  { ko: '속눈썹', en: 'eyelashes', read: '아이래시즈', emoji: '👁️' },
  { ko: '손목', en: 'wrist', read: '리스트', emoji: '⌚' },
  { ko: '발목', en: 'ankle', read: '앵클', emoji: '🦶' },
  { ko: '근육', alt: ['알통'], en: 'muscle', read: '머슬', emoji: '💪' },
  { ko: '두뇌', en: 'brain', read: '브레인', emoji: '🧠' },
  { ko: '콧수염', en: 'mustache', read: '머스태시', emoji: '🥸' },
  { ko: '눈물', en: 'tears', read: '티어스', emoji: '😢' },
  { ko: '목소리', en: 'voice', read: '보이스', emoji: '🗣️' },

  // ── 사람·직업 (추가) ──
  { ko: '운동선수', alt: ['선수'], en: 'athlete', read: '애슬리트', emoji: '🏅' },
  { ko: '축구선수', en: 'soccer player', read: '사커 플레이어', emoji: '⚽' },
  { ko: '발레리나', alt: ['발레'], en: 'ballerina', read: '발레리나', emoji: '🩰' },
  { ko: '댄서', alt: ['무용수'], en: 'dancer', read: '댄서', emoji: '💃' },
  { ko: '광대', alt: ['삐에로', '피에로'], en: 'clown', read: '클라운', emoji: '🤡' },
  { ko: '해적', alt: ['해적선장'], en: 'pirate', read: '파이럿', emoji: '🏴‍☠️' },
  { ko: '닌자', en: 'ninja', read: '닌자', emoji: '🥷' },
  { ko: '기사', alt: ['기사님'], en: 'knight', read: '나이트', emoji: '🛡️' },
  { ko: '인어', alt: ['인어공주'], en: 'mermaid', read: '머메이드', emoji: '🧜' },
  { ko: '괴물', alt: ['몬스터'], en: 'monster', read: '몬스터', emoji: '👾' },
  { ko: '도깨비', en: 'goblin', read: '고블린', emoji: '👹' },
  { ko: '우체부', alt: ['집배원', '우편배달부'], en: 'mail carrier', read: '메일 캐리어', emoji: '📮' },
  { ko: '조종사', alt: ['파일럿', '비행사'], en: 'pilot', read: '파일럿', emoji: '👨‍✈️' },
  { ko: '치과의사', alt: ['치과 선생님'], en: 'dentist', read: '덴티스트', emoji: '🦷' },
  { ko: '수의사', alt: ['수의사 선생님'], en: 'vet', read: '벳', emoji: '🩺' },
  { ko: '과학자', en: 'scientist', read: '사이언티스트', emoji: '🧑‍🔬' },
  { ko: '미용사', alt: ['헤어디자이너'], en: 'hairdresser', read: '헤어드레서', emoji: '💇' }
].forEach(w => { w.cat = 'body'; WORDS.push(w); });
