/* 단어 사전: 옷·동작·기분 — 계약
 *  CATS.push({ id, name, emoji })  ·  WORDS.push({ ko, alt:[], en, read, emoji, cat })
 *  - ko: 대표 한국어(매칭용), alt: 발음 변형·유의어(선택), en: 영어(소문자),
 *    read: 한글 발음 표기, emoji: 그림 1개, cat: 카테고리 id
 *  - en은 사전 전체에서 유일해야 함. 1글자 ko는 오탐 주의(가급적 2글자+)
 */
window.WORDS = window.WORDS || [];
window.CATS = window.CATS || [];

CATS.push({ id: 'clothes', name: '옷·동작·기분', emoji: '👕' });

[
  // ── 옷 ──
  { ko: '티셔츠', en: 't shirt', read: '티셔츠', emoji: '👕' },
  { ko: '바지', alt: ['긴바지'], en: 'pants', read: '팬츠', emoji: '👖' },
  { ko: '반바지', en: 'shorts', read: '쇼츠', emoji: '🩳' },
  { ko: '치마', en: 'skirt', read: '스커트', emoji: '👗' },
  { ko: '양말', en: 'socks', read: '삭스', emoji: '🧦' },
  { ko: '신발', alt: ['운동화'], en: 'shoes', read: '슈즈', emoji: '👟' },
  { ko: '부츠', alt: ['장화'], en: 'boots', read: '부츠', emoji: '🥾' },
  { ko: '슬리퍼', alt: ['실내화'], en: 'slippers', read: '슬리퍼', emoji: '🩴' },
  { ko: '모자', en: 'hat', read: '햇', emoji: '🎩' },
  { ko: '장갑', en: 'gloves', read: '글러브', emoji: '🧤' },
  { ko: '목도리', alt: ['스카프'], en: 'scarf', read: '스카프', emoji: '🧣' },
  { ko: '안경', en: 'glasses', read: '글래시스', emoji: '👓' },
  { ko: '선글라스', en: 'sunglasses', read: '썬글라스', emoji: '🕶️' },
  { ko: '외투', alt: ['코트', '점퍼'], en: 'coat', read: '코트', emoji: '🧥' },
  { ko: '넥타이', en: 'tie', read: '타이', emoji: '👔' },
  { ko: '왕관', en: 'crown', read: '크라운', emoji: '👑' },
  { ko: '반지', en: 'ring', read: '링', emoji: '💍' },
  { ko: '목걸이', en: 'necklace', read: '넥클리스', emoji: '📿' },
  { ko: '수영복', en: 'swimsuit', read: '스윔슈트', emoji: '🩱' },
  { ko: '속옷', alt: ['팬티'], en: 'underwear', read: '언더웨어', emoji: '🩲' },
  // ── 동작 ──
  { ko: '달리기', alt: ['뛰기'], en: 'run', read: '런', emoji: '🏃' },
  { ko: '점프', alt: ['폴짝'], en: 'jump', read: '점프', emoji: '🤸' },
  { ko: '걷기', en: 'walk', read: '워크', emoji: '🚶' },
  { ko: '먹기', en: 'eat', read: '잇', emoji: '🍽️' },
  { ko: '마시기', en: 'drink', read: '드링크', emoji: '🥤' },
  { ko: '잠자기', alt: ['코자', '자장자장'], en: 'sleep', read: '슬립', emoji: '😴' },
  { ko: '웃음', alt: ['웃기', '하하'], en: 'laugh', read: '래프', emoji: '😂' },
  { ko: '미소', alt: ['방긋'], en: 'smile', read: '스마일', emoji: '😊' },
  { ko: '울기', alt: ['울음', '엉엉'], en: 'cry', read: '크라이', emoji: '😭' },
  { ko: '춤추기', alt: ['댄스'], en: 'dance', read: '댄스', emoji: '💃' },
  { ko: '노래하기', alt: ['노래 부르기'], en: 'sing', read: '싱', emoji: '🎵' },
  { ko: '박수', alt: ['짝짝'], en: 'clap', read: '클랩', emoji: '👏' },
  { ko: '안기', alt: ['안아주기', '포옹'], en: 'hug', read: '허그', emoji: '🤗' },
  { ko: '뽀뽀', alt: ['입맞춤'], en: 'kiss', read: '키스', emoji: '😘' },
  { ko: '안녕', alt: ['안녕하세요'], en: 'hello', read: '헬로', emoji: '👋' },
  { ko: '수영', alt: ['수영하기'], en: 'swim', read: '스윔', emoji: '🏊' },
  { ko: '놀기', alt: ['놀이'], en: 'play', read: '플레이', emoji: '🛝' },
  { ko: '읽기', alt: ['책 읽기'], en: 'read', read: '리드', emoji: '📖' },
  { ko: '쓰기', alt: ['글쓰기'], en: 'write', read: '라이트', emoji: '✏️' },
  { ko: '그리기', alt: ['그림 그리기'], en: 'draw', read: '드로우', emoji: '🖍️' },
  { ko: '앉기', en: 'sit', read: '싯', emoji: '🪑' },
  { ko: '던지기', en: 'throw', read: '쓰로우', emoji: '🤾' },
  { ko: '올라가기', alt: ['오르기'], en: 'climb', read: '클라임', emoji: '🧗' },
  { ko: '날기', alt: ['날아가기'], en: 'fly', read: '플라이', emoji: '🕊️' },
  { ko: '씻기', alt: ['손 씻기'], en: 'wash', read: '워시', emoji: '🧼' },
  { ko: '말하기', alt: ['이야기'], en: 'talk', read: '토크', emoji: '🗣️' },
  { ko: '보기', alt: ['쳐다보기'], en: 'look', read: '룩', emoji: '👀' },
  { ko: '생각하기', alt: ['생각'], en: 'think', read: '씽크', emoji: '🤔' },
  { ko: '요리하기', alt: ['요리'], en: 'cook', read: '쿡', emoji: '🍳' },
  { ko: '청소', alt: ['청소하기'], en: 'clean', read: '클린', emoji: '🧹' },
  { ko: '숨기', alt: ['숨바꼭질'], en: 'hide', read: '하이드', emoji: '🙈' },
  // ── 기분 ──
  { ko: '행복', alt: ['기쁨', '행복해'], en: 'happy', read: '해피', emoji: '😃' },
  { ko: '슬픔', alt: ['슬퍼'], en: 'sad', read: '새드', emoji: '😢' },
  { ko: '화남', alt: ['화나', '화났어'], en: 'angry', read: '앵그리', emoji: '😠' },
  { ko: '졸림', alt: ['졸려'], en: 'sleepy', read: '슬리피', emoji: '🥱' },
  { ko: '사랑', alt: ['사랑해'], en: 'love', read: '러브', emoji: '❤️' },
  { ko: '무서움', alt: ['무서워'], en: 'scared', read: '스케어드', emoji: '😨' },
  { ko: '놀람', alt: ['깜짝'], en: 'surprise', read: '서프라이즈', emoji: '😲' },
  { ko: '신남', alt: ['신나'], en: 'excited', read: '익사이티드', emoji: '🤩' },
  { ko: '재미', alt: ['재밌어'], en: 'fun', read: '펀', emoji: '😆' },
  { ko: '아픔', alt: ['아파', '아야'], en: 'sick', read: '씩', emoji: '🤒' },
  { ko: '배고픔', alt: ['배고파'], en: 'hungry', read: '헝그리', emoji: '🤤' },
  { ko: '피곤', alt: ['피곤해'], en: 'tired', read: '타이어드', emoji: '😫' },
  { ko: '부끄러움', alt: ['부끄러워', '수줍음'], en: 'shy', read: '샤이', emoji: '😳' },

  // ── 옷 (추가) ──
  { ko: '원피스', alt: ['드레스'], en: 'dress', read: '드레스', emoji: '👗' },
  { ko: '스웨터', alt: ['니트'], en: 'sweater', read: '스웨터', emoji: '🧶' },
  { ko: '조끼', en: 'vest', read: '베스트', emoji: '🦺' },
  { ko: '잠옷', alt: ['파자마'], en: 'pajamas', read: '파자마', emoji: '🛌' },
  { ko: '턱받이', en: 'bib', read: '빕', emoji: '👶' },
  { ko: '멜빵바지', alt: ['멜빵'], en: 'overalls', read: '오버롤즈', emoji: '👖' },
  { ko: '샌들', alt: ['샌달'], en: 'sandals', read: '샌들즈', emoji: '👡' },
  { ko: '구두', en: 'dress shoes', read: '드레스 슈즈', emoji: '👞' },
  { ko: '하이힐', en: 'high heels', read: '하이 힐즈', emoji: '👠' },
  { ko: '귀마개', en: 'earmuffs', read: '이어머프스', emoji: '🎧' },
  { ko: '우비', alt: ['비옷', '우의'], en: 'raincoat', read: '레인코트', emoji: '☔' },
  { ko: '야구모자', alt: ['캡모자'], en: 'cap', read: '캡', emoji: '🧢' },
  { ko: '앞치마', en: 'apron', read: '에이프런', emoji: '🧑‍🍳' },
  { ko: '헬멧', alt: ['안전모'], en: 'helmet', read: '헬멧', emoji: '⛑️' },
  { ko: '마스크', en: 'mask', read: '마스크', emoji: '😷' },
  { ko: '지갑', en: 'wallet', read: '월릿', emoji: '👛' },
  { ko: '손목시계', en: 'watch', read: '워치', emoji: '⌚' },
  { ko: '팔찌', en: 'bracelet', read: '브레이슬릿', emoji: '📿' },
  { ko: '귀걸이', alt: ['귀고리'], en: 'earrings', read: '이어링즈', emoji: '💎' },
  { ko: '머리띠', en: 'headband', read: '헤드밴드', emoji: '🎀' },

  // ── 동작 (추가) ──
  { ko: '양치질', alt: ['양치', '이 닦기'], en: 'brush teeth', read: '브러시 티스', emoji: '🪥' },
  { ko: '목욕', alt: ['목욕하기'], en: 'take a bath', read: '테이크 어 배스', emoji: '🛁' },
  { ko: '찾기', alt: ['찾았다'], en: 'find', read: '파인드', emoji: '🔎' },
  { ko: '잡기', alt: ['공 잡기'], en: 'catch', read: '캐치', emoji: '⚾' },
  { ko: '밀기', en: 'push', read: '푸시', emoji: '🫸' },
  { ko: '당기기', en: 'pull', read: '풀', emoji: '🫷' },
  { ko: '구르기', alt: ['데굴데굴'], en: 'roll', read: '롤', emoji: '🤸' },
  { ko: '기어가기', alt: ['엉금엉금'], en: 'crawl', read: '크롤', emoji: '👶' },
  { ko: '스케이트', alt: ['스케이트 타기'], en: 'skate', read: '스케이트', emoji: '⛸️' },
  { ko: '흔들기', alt: ['흔들흔들'], en: 'shake', read: '셰이크', emoji: '🫨' },
  { ko: '돌기', alt: ['빙글빙글'], en: 'spin', read: '스핀', emoji: '💫' },
  { ko: '멈추기', alt: ['멈춰'], en: 'stop', read: '스탑', emoji: '🛑' },
  { ko: '듣기', alt: ['듣기 놀이'], en: 'listen', read: '리슨', emoji: '👂' },
  { ko: '냄새맡기', alt: ['킁킁'], en: 'smell', read: '스멜', emoji: '👃' },
  { ko: '노크', alt: ['똑똑'], en: 'knock', read: '노크', emoji: '✊' },
  { ko: '인사', alt: ['인사하기'], en: 'bow', read: '바우', emoji: '🙇' },
  { ko: '발차기', en: 'kick', read: '킥', emoji: '🦵' },
  { ko: '공부', alt: ['공부하기'], en: 'study', read: '스터디', emoji: '📚' },
  { ko: '기다리기', alt: ['기다려'], en: 'wait', read: '웨이트', emoji: '⏳' },
  { ko: '일어나기', alt: ['기상'], en: 'wake up', read: '웨이크 업', emoji: '⏰' },
  { ko: '눕기', alt: ['눕기 놀이'], en: 'lie down', read: '라이 다운', emoji: '🛏️' },
  { ko: '서기', alt: ['일어서기'], en: 'stand', read: '스탠드', emoji: '🧍' },

  // ── 기분·상태 (추가) ──
  { ko: '목마름', alt: ['목말라'], en: 'thirsty', read: '써스티', emoji: '🥤' },
  { ko: '심심함', alt: ['심심해'], en: 'bored', read: '보어드', emoji: '😐' },
  { ko: '용감함', alt: ['용감해', '씩씩해'], en: 'brave', read: '브레이브', emoji: '💪' },
  { ko: '궁금함', alt: ['궁금해'], en: 'curious', read: '큐리어스', emoji: '🤔' },
  { ko: '뿌듯함', alt: ['자랑스러워'], en: 'proud', read: '프라우드', emoji: '😌' },
  { ko: '걱정', alt: ['걱정돼'], en: 'worried', read: '워리드', emoji: '😟' },
  { ko: '편안함', alt: ['편안해'], en: 'calm', read: '캄', emoji: '🧘' },
  { ko: '최고', alt: ['최고야'], en: 'great', read: '그레이트', emoji: '👍' },
  { ko: '고마워', alt: ['감사합니다', '고맙습니다'], en: 'thank you', read: '땡큐', emoji: '🙏' },
  { ko: '미안해', alt: ['미안', '죄송합니다'], en: 'sorry', read: '쏘리', emoji: '😔' }
].forEach(w => { w.cat = 'clothes'; WORDS.push(w); });
