/* 단어 사전: 음식 — 계약
 *  CATS.push({ id, name, emoji })  ·  WORDS.push({ ko, alt:[], en, read, emoji, cat })
 *  - ko: 대표 한국어(매칭용), alt: 발음 변형·유의어(선택), en: 영어(소문자),
 *    read: 한글 발음 표기, emoji: 그림 1개, cat: 카테고리 id
 *  - en은 사전 전체에서 유일해야 함. 1글자 ko는 오탐 주의(가급적 2글자+)
 */
window.WORDS = window.WORDS || [];
window.CATS = window.CATS || [];

CATS.push({ id: 'food', name: '음식', emoji: '🍎' });

[
  // 과일
  { ko: '사과', alt: ['능금'], en: 'apple', read: '애플', emoji: '🍎' },
  { ko: '바나나', en: 'banana', read: '버내너', emoji: '🍌' },
  { ko: '포도', alt: ['청포도'], en: 'grape', read: '그레이프', emoji: '🍇' },
  { ko: '딸기', en: 'strawberry', read: '스트로베리', emoji: '🍓' },
  { ko: '수박', en: 'watermelon', read: '워터멜론', emoji: '🍉' },
  { ko: '오렌지', alt: ['주황색', '주황'], en: 'orange', read: '오렌지', emoji: '🍊' },
  { ko: '레몬', en: 'lemon', read: '레몬', emoji: '🍋' },
  { ko: '복숭아', alt: ['복숭이'], en: 'peach', read: '피치', emoji: '🍑' },
  { ko: '체리', alt: ['앵두'], en: 'cherry', read: '체리', emoji: '🍒' },
  { ko: '키위', en: 'kiwi', read: '키위', emoji: '🥝' },
  { ko: '파인애플', en: 'pineapple', read: '파인애플', emoji: '🍍' },
  { ko: '망고', en: 'mango', read: '망고', emoji: '🥭' },
  { ko: '멜론', alt: ['메론'], en: 'melon', read: '멜론', emoji: '🍈' },
  { ko: '블루베리', en: 'blueberry', read: '블루베리', emoji: '🫐' },
  { ko: '코코넛', en: 'coconut', read: '코코넛', emoji: '🥥' },
  { ko: '토마토', alt: ['방울토마토'], en: 'tomato', read: '토마토', emoji: '🍅' },
  { ko: '아보카도', en: 'avocado', read: '아보카도', emoji: '🥑' },
  // 채소
  { ko: '당근', en: 'carrot', read: '캐럿', emoji: '🥕' },
  { ko: '감자', en: 'potato', read: '포테이토', emoji: '🥔' },
  { ko: '고구마', en: 'sweet potato', read: '스위트 포테이토', emoji: '🍠' },
  { ko: '오이', en: 'cucumber', read: '큐컴버', emoji: '🥒' },
  { ko: '옥수수', alt: ['강냉이'], en: 'corn', read: '콘', emoji: '🌽' },
  { ko: '양파', en: 'onion', read: '어니언', emoji: '🧅' },
  { ko: '버섯', en: 'mushroom', read: '머시룸', emoji: '🍄' },
  { ko: '브로콜리', alt: ['브로컬리'], en: 'broccoli', read: '브로콜리', emoji: '🥦' },
  { ko: '호박', alt: ['단호박'], en: 'pumpkin', read: '펌킨', emoji: '🎃' },
  { ko: '가지', en: 'eggplant', read: '에그플랜트', emoji: '🍆' },
  { ko: '상추', alt: ['양상추'], en: 'lettuce', read: '레터스', emoji: '🥬' },
  { ko: '마늘', en: 'garlic', read: '갈릭', emoji: '🧄' },
  { ko: '완두콩', alt: ['완두'], en: 'pea', read: '피', emoji: '🫛' },
  { ko: '고추', alt: ['매운고추'], en: 'chili', read: '칠리', emoji: '🌶️' },
  { ko: '올리브', en: 'olive', read: '올리브', emoji: '🫒' },
  // 식사
  { ko: '빵', alt: ['식빵'], en: 'bread', read: '브레드', emoji: '🍞' },
  { ko: '밥', alt: ['쌀밥', '흰밥'], en: 'rice', read: '라이스', emoji: '🍚' },
  { ko: '피자', en: 'pizza', read: '피자', emoji: '🍕' },
  { ko: '햄버거', alt: ['버거'], en: 'hamburger', read: '햄버거', emoji: '🍔' },
  { ko: '치킨', alt: ['닭튀김', '후라이드'], en: 'fried chicken', read: '프라이드 치킨', emoji: '🍗' },
  { ko: '핫도그', alt: ['핫독'], en: 'hot dog', read: '핫 도그', emoji: '🌭' },
  { ko: '샌드위치', en: 'sandwich', read: '샌드위치', emoji: '🥪' },
  { ko: '스파게티', alt: ['파스타'], en: 'spaghetti', read: '스파게티', emoji: '🍝' },
  { ko: '국수', alt: ['잔치국수'], en: 'noodles', read: '누들스', emoji: '🍜' },
  { ko: '라면', en: 'ramen', read: '라멘', emoji: '🍜' },
  { ko: '만두', alt: ['왕만두'], en: 'dumpling', read: '덤플링', emoji: '🥟' },
  { ko: '계란', alt: ['달걀'], en: 'egg', read: '에그', emoji: '🥚' },
  { ko: '계란프라이', alt: ['달걀프라이'], en: 'fried egg', read: '프라이드 에그', emoji: '🍳' },
  { ko: '치즈', en: 'cheese', read: '치즈', emoji: '🧀' },
  { ko: '소시지', alt: ['쏘세지'], en: 'sausage', read: '소시지', emoji: '🌭' },
  { ko: '김치', en: 'kimchi', read: '김치', emoji: '🥬' },
  { ko: '수프', alt: ['스프'], en: 'soup', read: '수프', emoji: '🍲' },
  { ko: '샐러드', alt: ['사라다'], en: 'salad', read: '샐러드', emoji: '🥗' },
  { ko: '감자튀김', alt: ['감튀', '후렌치후라이'], en: 'french fries', read: '프렌치 프라이즈', emoji: '🍟' },
  { ko: '카레', alt: ['커리'], en: 'curry', read: '커리', emoji: '🍛' },
  { ko: '초밥', alt: ['스시'], en: 'sushi', read: '스시', emoji: '🍣' },
  { ko: '베이컨', en: 'bacon', read: '베이컨', emoji: '🥓' },
  { ko: '버터', en: 'butter', read: '버터', emoji: '🧈' },
  { ko: '고기', alt: ['소고기', '돼지고기'], en: 'meat', read: '미트', emoji: '🍖' },
  { ko: '스테이크', en: 'steak', read: '스테이크', emoji: '🥩' },
  // 간식·디저트
  { ko: '아이스크림', alt: ['아이스'], en: 'ice cream', read: '아이스크림', emoji: '🍦' },
  { ko: '사탕', alt: ['캔디'], en: 'candy', read: '캔디', emoji: '🍬' },
  { ko: '초콜릿', alt: ['초코', '초콜렛'], en: 'chocolate', read: '초콜릿', emoji: '🍫' },
  { ko: '케이크', alt: ['케익', '케잌'], en: 'cake', read: '케이크', emoji: '🎂' },
  { ko: '쿠키', en: 'cookie', read: '쿠키', emoji: '🍪' },
  { ko: '과자', alt: ['까까'], en: 'snack', read: '스낵', emoji: '🥨' },
  { ko: '도넛', alt: ['도너츠'], en: 'donut', read: '도넛', emoji: '🍩' },
  { ko: '젤리', en: 'jelly', read: '젤리', emoji: '🍬' },
  { ko: '팝콘', en: 'popcorn', read: '팝콘', emoji: '🍿' },
  { ko: '와플', en: 'waffle', read: '와플', emoji: '🧇' },
  { ko: '팬케이크', alt: ['핫케이크'], en: 'pancake', read: '팬케이크', emoji: '🥞' },
  { ko: '요구르트', alt: ['요거트', '야쿠르트'], en: 'yogurt', read: '요거트', emoji: '🥛' },
  { ko: '꿀', alt: ['허니'], en: 'honey', read: '허니', emoji: '🍯' },
  { ko: '파이', alt: ['호박파이'], en: 'pie', read: '파이', emoji: '🥧' },
  { ko: '컵케이크', en: 'cupcake', read: '컵케이크', emoji: '🧁' },
  { ko: '머핀', en: 'muffin', read: '머핀', emoji: '🧁' },
  { ko: '떡', alt: ['꿀떡'], en: 'rice cake', read: '라이스 케이크', emoji: '🍡' },
  { ko: '푸딩', en: 'pudding', read: '푸딩', emoji: '🍮' },
  // 마실 것
  { ko: '물', alt: ['마실물'], en: 'water', read: '워터', emoji: '💧' },
  { ko: '우유', en: 'milk', read: '밀크', emoji: '🥛' },
  { ko: '주스', alt: ['쥬스'], en: 'juice', read: '주스', emoji: '🧃' },
  { ko: '코코아', alt: ['핫초코'], en: 'cocoa', read: '코코아', emoji: '☕' },
  { ko: '레모네이드', alt: ['레몬에이드'], en: 'lemonade', read: '레모네이드', emoji: '🍹' },
  { ko: '밀크셰이크', alt: ['셰이크', '쉐이크'], en: 'milkshake', read: '밀크셰이크', emoji: '🥤' },
  { ko: '콜라', en: 'cola', read: '콜라', emoji: '🥤' },
  { ko: '스무디', en: 'smoothie', read: '스무디', emoji: '🧋' },
  // 식기
  { ko: '숟가락', alt: ['수저', '숫가락'], en: 'spoon', read: '스푼', emoji: '🥄' },
  { ko: '포크', en: 'fork', read: '포크', emoji: '🍴' },
  { ko: '컵', alt: ['물컵'], en: 'cup', read: '컵', emoji: '☕' },
  { ko: '접시', en: 'plate', read: '플레이트', emoji: '🍽️' },
  { ko: '젓가락', alt: ['저까락'], en: 'chopsticks', read: '촙스틱스', emoji: '🥢' },
  { ko: '그릇', alt: ['밥그릇'], en: 'bowl', read: '보울', emoji: '🥣' },
  // 한국 음식
  { ko: '김밥', en: 'gimbap', read: '김밥', emoji: '🍙' },
  { ko: '떡볶이', alt: ['떡볶기'], en: 'tteokbokki', read: '떡볶이', emoji: '🍢' },
  { ko: '비빔밥', en: 'bibimbap', read: '비빔밥', emoji: '🥘' },
  { ko: '불고기', en: 'bulgogi', read: '불고기', emoji: '🥩' },
  { ko: '미역국', en: 'seaweed soup', read: '시위드 수프', emoji: '🍲' },
  { ko: '갈비', en: 'ribs', read: '립스', emoji: '🍖' },
  { ko: '잡채', en: 'japchae', read: '잡채', emoji: '🍜' },
  { ko: '삼계탕', en: 'samgyetang', read: '삼계탕', emoji: '🍲' },
  { ko: '호떡', en: 'hotteok', read: '호떡', emoji: '🥞' },
  { ko: '붕어빵', alt: ['잉어빵'], en: 'fish bread', read: '피시 브레드', emoji: '🐟' },
  { ko: '송편', en: 'songpyeon', read: '송편', emoji: '🍡' },
  { ko: '팥빙수', alt: ['빙수'], en: 'shaved ice', read: '셰이브드 아이스', emoji: '🍧' },
  { ko: '어묵', alt: ['오뎅'], en: 'fish cake', read: '피시 케이크', emoji: '🍢' },
  { ko: '부침개', alt: ['파전'], en: 'korean pancake', read: '코리안 팬케이크', emoji: '🥞' },
  { ko: '삼겹살', en: 'pork belly', read: '포크 벨리', emoji: '🥓' },
  { ko: '찌개', alt: ['된장찌개', '김치찌개'], en: 'stew', read: '스튜', emoji: '🍲' },
  { ko: '주먹밥', en: 'rice ball', read: '라이스 볼', emoji: '🍙' },
  { ko: '떡국', en: 'rice cake soup', read: '라이스 케이크 수프', emoji: '🍲' },
  { ko: '짜장면', alt: ['자장면'], en: 'jajangmyeon', read: '짜장면', emoji: '🍜' },
  // 과일·견과·채소 더
  { ko: '파파야', en: 'papaya', read: '파파야', emoji: '🥭' },
  { ko: '석류', en: 'pomegranate', read: '포미그래닛', emoji: '🍎' },
  { ko: '자두', en: 'plum', read: '플럼', emoji: '🟣' },
  { ko: '홍시', alt: ['단감'], en: 'persimmon', read: '퍼시먼', emoji: '🍊' },
  { ko: '감귤', alt: ['밀감'], en: 'tangerine', read: '탠저린', emoji: '🍊' },
  { ko: '라임', en: 'lime', read: '라임', emoji: '🍋' },
  { ko: '살구', en: 'apricot', read: '애프리콧', emoji: '🍑' },
  { ko: '밤톨', alt: ['알밤'], en: 'chestnut', read: '체스트넛', emoji: '🌰' },
  { ko: '땅콩', en: 'peanut', read: '피넛', emoji: '🥜' },
  { ko: '호두', en: 'walnut', read: '월넛', emoji: '🌰' },
  { ko: '아몬드', en: 'almond', read: '아몬드', emoji: '🥜' },
  { ko: '양배추', en: 'cabbage', read: '캐비지', emoji: '🥬' },
  { ko: '배추', en: 'napa cabbage', read: '나파 캐비지', emoji: '🥬' },
  { ko: '시금치', en: 'spinach', read: '스피니치', emoji: '🍃' },
  { ko: '파프리카', alt: ['피망'], en: 'bell pepper', read: '벨 페퍼', emoji: '🫑' },
  { ko: '콩알', alt: ['강낭콩'], en: 'beans', read: '빈즈', emoji: '🫘' },
  { ko: '생강', en: 'ginger', read: '진저', emoji: '🫚' },
  { ko: '대파', alt: ['쪽파'], en: 'green onion', read: '그린 어니언', emoji: '🧅' },
  // 간식·디저트 더
  { ko: '마카롱', en: 'macaron', read: '마카롱', emoji: '🍪' },
  { ko: '풍선껌', en: 'gum', read: '껌', emoji: '🍬' },
  { ko: '츄러스', alt: ['추로스'], en: 'churros', read: '츄러스', emoji: '🥨' },
  { ko: '크루아상', alt: ['크로와상'], en: 'croissant', read: '크루아상', emoji: '🥐' },
  { ko: '바게트', alt: ['바게뜨'], en: 'baguette', read: '바게트', emoji: '🥖' },
  { ko: '프레첼', alt: ['프레즐'], en: 'pretzel', read: '프레첼', emoji: '🥨' },
  { ko: '마시멜로', alt: ['마쉬멜로'], en: 'marshmallow', read: '마시멜로', emoji: '🍬' },
  { ko: '솜사탕', en: 'cotton candy', read: '코튼 캔디', emoji: '🍭' },
  { ko: '막대사탕', alt: ['롤리팝'], en: 'lollipop', read: '롤리팝', emoji: '🍭' },
  { ko: '아이스바', alt: ['하드'], en: 'popsicle', read: '팝시클', emoji: '🍨' },
  { ko: '카스테라', alt: ['카스텔라'], en: 'castella', read: '카스테라', emoji: '🍰' },
  // 요리·식사 더
  { ko: '시리얼', en: 'cereal', read: '시리얼', emoji: '🥣' },
  { ko: '딸기잼', en: 'jam', read: '잼', emoji: '🫙' },
  { ko: '오믈렛', en: 'omelet', read: '오믈렛', emoji: '🍳' },
  { ko: '타코', en: 'taco', read: '타코', emoji: '🌮' },
  { ko: '부리토', alt: ['브리또'], en: 'burrito', read: '부리토', emoji: '🌯' },
  { ko: '토스트', en: 'toast', read: '토스트', emoji: '🍞' },
  { ko: '크래커', en: 'cracker', read: '크래커', emoji: '🍘' },
  { ko: '새우튀김', en: 'fried shrimp', read: '프라이드 쉬림프', emoji: '🍤' },
  { ko: '미트볼', en: 'meatball', read: '미트볼', emoji: '🧆' },
  { ko: '피클', en: 'pickle', read: '피클', emoji: '🥒' },
  { ko: '케첩', alt: ['케찹'], en: 'ketchup', read: '케첩', emoji: '🍅' },
  { ko: '소금', en: 'salt', read: '솔트', emoji: '🧂' },
  { ko: '설탕', en: 'sugar', read: '슈거', emoji: '🧂' },
  // 마실 것 더
  { ko: '녹차', en: 'green tea', read: '그린 티', emoji: '🍵' },
  { ko: '딸기우유', alt: ['딸기맛우유'], en: 'strawberry milk', read: '스트로베리 밀크', emoji: '🍓' },
  { ko: '바나나우유', en: 'banana milk', read: '버내너 밀크', emoji: '🍌' }
].forEach(w => { w.cat = 'food'; WORDS.push(w); });
