/* 단어 사전: 자연 — 계약
 *  CATS.push({ id, name, emoji })  ·  WORDS.push({ ko, alt:[], en, read, emoji, cat })
 *  - ko: 대표 한국어(매칭용), alt: 발음 변형·유의어(선택), en: 영어(소문자),
 *    read: 한글 발음 표기, emoji: 그림 1개, cat: 카테고리 id
 *  - en은 사전 전체에서 유일해야 함. 1글자 ko는 오탐 주의(가급적 2글자+)
 *  - '물(water)'은 음식 카테고리 소관이라 여기서 제외
 */
window.WORDS = window.WORDS || [];
window.CATS = window.CATS || [];

CATS.push({ id: 'nature', name: '자연', emoji: '🌳' });

[
  // ── 하늘 ──
  { ko: '해', alt: ['해님', '태양'], en: 'sun', read: '썬', emoji: '☀️' },
  { ko: '햇살', alt: ['햇빛'], en: 'sunshine', read: '썬샤인', emoji: '🌞' },
  { ko: '달', alt: ['달님'], en: 'moon', read: '문', emoji: '🌙' },
  { ko: '보름달', en: 'full moon', read: '풀 문', emoji: '🌕' },
  { ko: '작은 별', alt: ['별님', '반짝별'], en: 'little star', read: '리틀 스타', emoji: '⭐' },
  { ko: '별똥별', en: 'shooting star', read: '슈팅 스타', emoji: '🌠' },
  { ko: '구름', en: 'cloud', read: '클라우드', emoji: '☁️' },
  { ko: '하늘', en: 'sky', read: '스카이', emoji: '🌤️' },
  { ko: '무지개', en: 'rainbow', read: '레인보우', emoji: '🌈' },
  { ko: '아침', en: 'morning', read: '모닝', emoji: '🌅' },
  { ko: '노을', en: 'sunset', read: '썬셋', emoji: '🌇' },
  { ko: '우주', en: 'space', read: '스페이스', emoji: '🌌' },
  { ko: '지구', en: 'earth', read: '어스', emoji: '🌍' },
  { ko: '행성', en: 'planet', read: '플래닛', emoji: '🪐' },
  // ── 날씨 ──
  { ko: '비', alt: ['빗방울'], en: 'rain', read: '레인', emoji: '🌧️' },
  { ko: '눈', alt: ['하얀 눈', '눈송이'], en: 'snow', read: '스노우', emoji: '❄️' },
  { ko: '눈사람', en: 'snowman', read: '스노우맨', emoji: '⛄' },
  { ko: '바람', en: 'wind', read: '윈드', emoji: '🌬️' },
  { ko: '공기', en: 'air', read: '에어', emoji: '💨' },
  { ko: '번개', en: 'lightning', read: '라이트닝', emoji: '⚡' },
  { ko: '천둥', en: 'thunder', read: '썬더', emoji: '⛈️' },
  { ko: '폭풍', en: 'storm', read: '스톰', emoji: '🌀' },
  { ko: '회오리', alt: ['회오리바람'], en: 'tornado', read: '토네이도', emoji: '🌪️' },
  { ko: '안개', en: 'fog', read: '포그', emoji: '🌫️' },
  { ko: '얼음', en: 'ice', read: '아이스', emoji: '🧊' },
  // ── 계절 ──
  { ko: '봄', en: 'spring', read: '스프링', emoji: '🌺' },
  { ko: '여름', en: 'summer', read: '썸머', emoji: '⛱️' },
  { ko: '가을', en: 'fall', read: '폴', emoji: '🍂' },
  { ko: '겨울', en: 'winter', read: '윈터', emoji: '☃️' },
  // ── 땅·물 ──
  { ko: '산', en: 'mountain', read: '마운틴', emoji: '🏔️' },
  { ko: '언덕', en: 'hill', read: '힐', emoji: '⛰️' },
  { ko: '바다', alt: ['바닷물'], en: 'sea', read: '씨', emoji: '🌊' },
  { ko: '파도', en: 'wave', read: '웨이브', emoji: '🏄' },
  { ko: '강', alt: ['강물'], en: 'river', read: '리버', emoji: '🏞️' },
  { ko: '호수', en: 'lake', read: '레이크', emoji: '⛵' },
  { ko: '폭포', en: 'waterfall', read: '워터폴', emoji: '💦' },
  { ko: '돌', alt: ['돌멩이'], en: 'stone', read: '스톤', emoji: '🪨' },
  { ko: '바위', en: 'rock', read: '락', emoji: '🗿' },
  { ko: '모래', en: 'sand', read: '샌드', emoji: '🏖️' },
  { ko: '사막', en: 'desert', read: '데저트', emoji: '🏜️' },
  { ko: '동굴', en: 'cave', read: '케이브', emoji: '🕳️' },
  { ko: '화산', en: 'volcano', read: '볼케이노', emoji: '🌋' },
  { ko: '불', en: 'fire', read: '파이어', emoji: '🔥' },
  // ── 식물 ──
  { ko: '나무', en: 'tree', read: '트리', emoji: '🌳' },
  { ko: '숲', alt: ['숲속'], en: 'forest', read: '포레스트', emoji: '🌲' },
  { ko: '꽃', alt: ['꽃송이'], en: 'flower', read: '플라워', emoji: '💐' },
  { ko: '나뭇잎', alt: ['잎사귀'], en: 'leaf', read: '리프', emoji: '🍃' },
  { ko: '나뭇가지', en: 'branch', read: '브랜치', emoji: '🪵' },
  { ko: '잔디', alt: ['풀잎'], en: 'grass', read: '그라스', emoji: '🌿' },
  { ko: '씨앗', en: 'seed', read: '씨드', emoji: '🌰' },
  { ko: '새싹', en: 'sprout', read: '스프라우트', emoji: '🌱' },
  { ko: '장미', en: 'rose', read: '로즈', emoji: '🌹' },
  { ko: '해바라기', en: 'sunflower', read: '썬플라워', emoji: '🌻' },
  { ko: '튤립', en: 'tulip', read: '튤립', emoji: '🌷' },
  { ko: '데이지', en: 'daisy', read: '데이지', emoji: '🌼' },
  { ko: '벚꽃', en: 'cherry blossom', read: '체리 블라섬', emoji: '🌸' },
  { ko: '단풍잎', alt: ['단풍'], en: 'maple', read: '메이플', emoji: '🍁' },
  { ko: '클로버', alt: ['네잎클로버'], en: 'clover', read: '클로버', emoji: '🍀' },
  { ko: '야자수', en: 'palm tree', read: '팜 트리', emoji: '🌴' },
  { ko: '선인장', en: 'cactus', read: '캑터스', emoji: '🌵' },
  { ko: '대나무', en: 'bamboo', read: '뱀부', emoji: '🎋' },
  { ko: '섬', en: 'island', read: '아일랜드', emoji: '🏝️' },
  // ── 날씨 더 ──
  { ko: '이슬비', alt: ['가랑비'], en: 'drizzle', read: '드리즐', emoji: '🌦️' },
  { ko: '소나기', en: 'rain shower', read: '레인 샤워', emoji: '🌧️' },
  { ko: '태풍', en: 'typhoon', read: '타이푼', emoji: '🌀' },
  { ko: '우박', en: 'hail', read: '헤일', emoji: '🌨️' },
  { ko: '서리', en: 'frost', read: '프로스트', emoji: '❄️' },
  { ko: '이슬', en: 'dew', read: '듀', emoji: '💧' },
  { ko: '고드름', en: 'icicle', read: '아이시클', emoji: '🧊' },
  { ko: '진눈깨비', en: 'sleet', read: '슬리트', emoji: '🌨️' },
  { ko: '장마', en: 'rainy season', read: '레이니 시즌', emoji: '☔' },
  // ── 하늘·우주 더 ──
  { ko: '혜성', en: 'comet', read: '코밋', emoji: '☄️' },
  { ko: '은하수', alt: ['은하'], en: 'galaxy', read: '갤럭시', emoji: '🌌' },
  { ko: '별자리', en: 'constellation', read: '컨스털레이션', emoji: '✨' },
  { ko: '새벽', en: 'dawn', read: '던', emoji: '🌄' },
  { ko: '밤하늘', en: 'night sky', read: '나이트 스카이', emoji: '🌃' },
  { ko: '저녁', en: 'evening', read: '이브닝', emoji: '🌆' },
  { ko: '달빛', en: 'moonlight', read: '문라이트', emoji: '🌝' },
  { ko: '오로라', en: 'aurora', read: '오로라', emoji: '🌌' },
  // ── 땅·물 더 ──
  { ko: '절벽', en: 'cliff', read: '클리프', emoji: '⛰️' },
  { ko: '계곡', en: 'valley', read: '밸리', emoji: '🏞️' },
  { ko: '연못', en: 'pond', read: '폰드', emoji: '🪷' },
  { ko: '들판', en: 'field', read: '필드', emoji: '🌾' },
  { ko: '진흙', en: 'mud', read: '머드', emoji: '🟤' },
  { ko: '빙하', en: 'glacier', read: '글레이시어', emoji: '🧊' },
  { ko: '온천', en: 'hot spring', read: '핫 스프링', emoji: '♨️' },
  { ko: '웅덩이', en: 'puddle', read: '퍼들', emoji: '💦' },
  { ko: '시냇물', alt: ['개울'], en: 'stream', read: '스트림', emoji: '🏞️' },
  // ── 식물 더 ──
  { ko: '민들레', en: 'dandelion', read: '댄딜라이언', emoji: '🌼' },
  { ko: '소나무', en: 'pine tree', read: '파인 트리', emoji: '🌲' },
  { ko: '단풍나무', en: 'maple tree', read: '메이플 트리', emoji: '🍁' },
  { ko: '버드나무', en: 'willow', read: '윌로우', emoji: '🌳' },
  { ko: '은행나무', en: 'ginkgo', read: '깅코', emoji: '🍂' },
  { ko: '이끼', en: 'moss', read: '모스', emoji: '🌿' },
  { ko: '덩굴', alt: ['넝쿨'], en: 'vine', read: '바인', emoji: '🌿' },
  { ko: '갈대', en: 'reed', read: '리드', emoji: '🌾' },
  { ko: '연꽃', en: 'lotus', read: '로터스', emoji: '🪷' },
  { ko: '나팔꽃', en: 'morning glory', read: '모닝 글로리', emoji: '🌺' },
  { ko: '카네이션', en: 'carnation', read: '카네이션', emoji: '💮' },
  { ko: '코스모스', en: 'cosmos', read: '코스모스', emoji: '🌸' },
  { ko: '라벤더', en: 'lavender', read: '라벤더', emoji: '🪻' },
  { ko: '백합', en: 'lily', read: '릴리', emoji: '🌷' },
  { ko: '도토리', en: 'acorn', read: '에이콘', emoji: '🌰' },
  // ── 자연현상 ──
  { ko: '그림자', en: 'shadow', read: '섀도우', emoji: '👤' },
  { ko: '메아리', en: 'echo', read: '에코', emoji: '🗣️' },
  { ko: '거품', en: 'foam', read: '폼', emoji: '🫧' },
  { ko: '물방울', en: 'water drop', read: '워터 드롭', emoji: '💧' },
  { ko: '수증기', en: 'steam', read: '스팀', emoji: '♨️' },
  { ko: '모닥불', alt: ['캠프파이어'], en: 'campfire', read: '캠프파이어', emoji: '🔥' },
  { ko: '연기', en: 'smoke', read: '스모크', emoji: '💨' }
].forEach(w => { w.cat = 'nature'; WORDS.push(w); });
