/* 일본어 낱말 — 집·물건
 * 계약과 read(한글 발음) 표기 규칙은 animals.js 머리 주석 참고.
 */
window.WORDS_JA = window.WORDS_JA || []; window.CATS_JA = window.CATS_JA || [];

CATS_JA.push({ id: 'home', name: '🏠 집·물건', emoji: '🏠' });

[
  /* --- 집 안 --- */
  { ko: '집', ja: 'いえ', kanji: '家', read: '이에', emoji: '🏠' },
  { ko: '방', ja: 'へや', kanji: '部屋', read: '헤야', emoji: '🛏️' },
  { ko: '문', ja: 'ドア', read: '도아', emoji: '🚪' },
  { ko: '창문', ja: 'まど', kanji: '窓', read: '마도', emoji: '🪟' },
  { ko: '침대', ja: 'ベッド', read: '벳도', emoji: '🛏️' },
  { ko: '의자', ja: 'いす', kanji: '椅子', read: '이스', emoji: '🪑' },
  { ko: '책상', ja: 'つくえ', kanji: '机', read: '츠쿠에', emoji: '🪑' },
  { ko: '소파', ja: 'ソファ', read: '소파', emoji: '🛋️' },
  { ko: '화장실', ja: 'トイレ', read: '토이레', emoji: '🚽' },
  { ko: '부엌', ja: 'だいどころ', kanji: '台所', read: '다이도코로', emoji: '🍳' },
  { ko: '계단', ja: 'かいだん', kanji: '階段', read: '카이당', emoji: '🪜' },
  { ko: '거울', ja: 'かがみ', kanji: '鏡', read: '카가미', emoji: '🪞' },
  { ko: '시계', ja: 'とけい', kanji: '時計', read: '토케이', emoji: '⏰' },
  { ko: '베개', ja: 'まくら', kanji: '枕', read: '마쿠라', emoji: '🛏️' },
  { ko: '이불', ja: 'ふとん', kanji: '布団', read: '후통', emoji: '🛌' },
  { ko: '커튼', ja: 'カーテン', read: '카아텡', emoji: '🪟' },
  /* --- 씻는 것 --- */
  { ko: '칫솔', ja: 'はブラシ', kanji: '歯ブラシ', read: '하부라시', emoji: '🪥' },
  { ko: '치약', ja: 'はみがきこ', kanji: '歯磨き粉', read: '하미가키코', emoji: '🪥' },
  { ko: '비누', ja: 'せっけん', kanji: '石鹸', read: '섹켕', emoji: '🧼' },
  { ko: '수건', ja: 'タオル', read: '타오루', emoji: '🧻' },
  { ko: '욕조', ja: 'おふろ', kanji: 'お風呂', read: '오후로', emoji: '🛁' },
  /* --- 살림살이 --- */
  { ko: '우산', ja: 'かさ', kanji: '傘', read: '카사', emoji: '☂️' },
  { ko: '열쇠', ja: 'かぎ', kanji: '鍵', read: '카기', emoji: '🔑' },
  { ko: '전화', ja: 'でんわ', kanji: '電話', read: '뎅와', emoji: '📞' },
  { ko: '휴대폰', ja: 'スマホ', read: '스마호', emoji: '📱' },
  { ko: '텔레비전', alt: ['티브이'], ja: 'テレビ', read: '테레비', emoji: '📺' },
  { ko: '컴퓨터', ja: 'パソコン', read: '파소콩', emoji: '💻' },
  { ko: '카메라', ja: 'カメラ', read: '카메라', emoji: '📷' },
  { ko: '전등', alt: ['불빛'], ja: 'でんき', kanji: '電気', read: '뎅키', emoji: '💡' },
  { ko: '쓰레기통', ja: 'ごみばこ', read: '고미바코', emoji: '🗑️' },
  { ko: '빗자루', ja: 'ほうき', kanji: '箒', read: '호우키', emoji: '🧹' },
  { ko: '냉장고', ja: 'れいぞうこ', kanji: '冷蔵庫', read: '레이조우코', emoji: '🧊' },
  { ko: '세탁기', ja: 'せんたくき', kanji: '洗濯機', read: '센타쿠키', emoji: '🧺' },
  { ko: '청소기', ja: 'そうじき', kanji: '掃除機', read: '소우지키', emoji: '🧹' },
  { ko: '선풍기', ja: 'せんぷうき', kanji: '扇風機', read: '셈푸우키', emoji: '🌀' },
  { ko: '냄비', ja: 'なべ', kanji: '鍋', read: '나베', emoji: '🍲' },
  { ko: '도시락', ja: 'おべんとう', kanji: 'お弁当', read: '오벤토우', emoji: '🍱' },
  { ko: '물통', ja: 'すいとう', kanji: '水筒', read: '스이토우', emoji: '🧴' },
  { ko: '빨대', ja: 'ストロー', read: '스토로오', emoji: '🥤' },
  /* --- 공부와 그리기 --- */
  { ko: '책', ja: 'ほん', kanji: '本', read: '홍', emoji: '📚' },
  { ko: '공책', ja: 'ノート', read: '노오토', emoji: '📓' },
  { ko: '연필', ja: 'えんぴつ', kanji: '鉛筆', read: '엠피츠', emoji: '✏️' },
  { ko: '색연필', ja: 'いろえんぴつ', kanji: '色鉛筆', read: '이로엠피츠', emoji: '🖍️' },
  { ko: '크레용', ja: 'クレヨン', read: '쿠레용', emoji: '🖍️' },
  { ko: '지우개', ja: 'けしゴム', kanji: '消しゴム', read: '케시고무', emoji: '🧽' },
  { ko: '필통', ja: 'ふでばこ', kanji: '筆箱', read: '후데바코', emoji: '✏️' },
  { ko: '종이', ja: 'かみ', kanji: '紙', read: '카미', emoji: '📄' },
  { ko: '가위', ja: 'はさみ', kanji: '鋏', read: '하사미', emoji: '✂️' },
  { ko: '풀', ja: 'のり', kanji: '糊', read: '노리', emoji: '🧴' },
  { ko: '가방', ja: 'かばん', kanji: '鞄', read: '카방', emoji: '🎒' },
  { ko: '붓', ja: 'ふで', kanji: '筆', read: '후데', emoji: '🖌️' },
  { ko: '물감', ja: 'えのぐ', kanji: '絵の具', read: '에노구', emoji: '🎨' },
  { ko: '스티커', ja: 'シール', read: '시이루', emoji: '🏷️' },
  { ko: '편지', ja: 'てがみ', kanji: '手紙', read: '테가미', emoji: '✉️' },
  { ko: '사진', ja: 'しゃしん', kanji: '写真', read: '샤싱', emoji: '📷' },
  { ko: '그림', ja: 'え', kanji: '絵', read: '에', emoji: '🎨' },
  { ko: '돋보기', ja: 'むしめがね', kanji: '虫眼鏡', read: '무시메가네', emoji: '🔍' },
  { ko: '망원경', ja: 'ぼうえんきょう', kanji: '望遠鏡', read: '보우엥쿄우', emoji: '🔭' },
  /* --- 놀잇감 --- */
  { ko: '장난감', ja: 'おもちゃ', read: '오모챠', emoji: '🧸' },
  { ko: '공', ja: 'ボール', read: '보오루', emoji: '⚽' },
  { ko: '풍선', ja: 'ふうせん', kanji: '風船', read: '후우셍', emoji: '🎈' },
  { ko: '인형', ja: 'にんぎょう', kanji: '人形', read: '닝교우', emoji: '🎎' },
  { ko: '곰인형', ja: 'ぬいぐるみ', read: '누이구루미', emoji: '🧸' },
  { ko: '로봇', ja: 'ロボット', read: '로봇토', emoji: '🤖' },
  { ko: '블록', ja: 'つみき', kanji: '積み木', read: '츠미키', emoji: '🧱' },
  { ko: '퍼즐', ja: 'パズル', read: '파즈루', emoji: '🧩' },
  { ko: '주사위', ja: 'さいころ', read: '사이코로', emoji: '🎲' },
  { ko: '그네', ja: 'ブランコ', read: '부랑코', emoji: '🛝' },
  { ko: '미끄럼틀', ja: 'すべりだい', kanji: '滑り台', read: '스베리다이', emoji: '🛝' },
  { ko: '피아노', ja: 'ピアノ', read: '피아노', emoji: '🎹' },
  { ko: '기타', ja: 'ギター', read: '기타아', emoji: '🎸' },
  { ko: '드럼', alt: ['북'], ja: 'たいこ', kanji: '太鼓', read: '타이코', emoji: '🥁' },
  { ko: '선물', ja: 'プレゼント', read: '푸레젠토', emoji: '🎁' },
  { ko: '돈', ja: 'おかね', kanji: 'お金', read: '오카네', emoji: '💰' },
  { ko: '동전', ja: 'コイン', read: '코잉', emoji: '🪙' },
  { ko: '촛불', ja: 'ろうそく', kanji: '蝋燭', read: '로우소쿠', emoji: '🕯️' },
  { ko: '상자', ja: 'はこ', kanji: '箱', read: '하코', emoji: '📦' },
  { ko: '리본', ja: 'リボン', read: '리봉', emoji: '🎀' },
  { ko: '신문', ja: 'しんぶん', kanji: '新聞', read: '심붕', emoji: '📰' }
].forEach(w => { w.cat = 'home'; WORDS_JA.push(w); });
